---
parameters:
  allowUsers:
   -"admin"
   -"vagrant"
  passwordAuthentication: "yes"
  permitRootLogin: "no"
  port: 22
  nginx_conf: "nginx.conf"
  postfix_config_content: "relay_domains = orsyp.com"
  capistrano_script: "modules/sd_api/capistrano.sh"
environment: "development"
